name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22' ] # 你可以添加更多版本
        os-arch:
          - { os: 'windows', arch: 'amd64' }
          - { os: 'windows', arch: '386' }
          - { os: 'darwin', arch: 'amd64' }
          - { os: 'darwin', arch: 'arm64' }
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: |
        GOOS=${{ matrix.os-arch.os }} GOARCH=${{ matrix.os-arch.arch }} go build -v -o ./bin/app-${{ matrix.os-arch.os }}-${{ matrix.os-arch.arch }} ./...

    - name: Test
      run: go test -v ./...
