name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [amd64, 386, arm64]
        include:
          - os: windows-latest
            architecture: amd64
          - os: windows-latest
            architecture: 386
          - os: macos-latest
            architecture: amd64
          - os: macos-latest
            architecture: arm64
        go-version: [1.22]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Display Go version
      run: go version

    - name: Build
      env:
        GOARCH: ${{ matrix.architecture }}
      run: go build -o DingTalkLiveDownload -v ./...

    - name: Run tests
      env:
        GOARCH: ${{ matrix.architecture }}
      run: go test -v ./...

    - name: Archive production artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: DingTalkLiveDownload-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.go-version }}
        path: ./DingTalkLiveDownload
